prompts:
  - role: system
    content: |-
      Give the best possible answer and nothing else.
  - role: user
    content: |-
      Add spaces to make each text line meaningful.
      Don't add spaces if not possible to make a text line meaningful.
      Examples:
      Input: 1. howareyou, Output: 1. how are you. Comment: Meaningful text line can be produced by adding spaces.
      Input: 1. dsvhwjeb34, Output: 1. dsvhwjeb34. Comment: Meaningful text line can't be produced by adding spaces.

separators:
  # Separators used when constructing prompt
  # Newline separators are better here as otherwise the model `GPT-3.5-turbo` combines adjacent text lines in the input
  line_sep: "\n"
  prompt_sep: "\n"
  index_sep: ")"

model:
  name: gpt-3.5-turbo
  max_tokens: 4096
  temperature: 0

logs:
  dir: logs
  file: log

input:
  file: text_lines